on:
  push:
    branches:
      - main
jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: "eu-west-1"
      - name: Install dependencies
        run: npm ci
      - name: Synth stack
        run: npm run synth
      - name: Bootstrap stack
        run: npm run bootstrap
      - name: Deploy stack
        run: cdk deploy --require-approval never
